image: node:latest

stages:
  - install
  - validation
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

prettier:
  stage: validation
  dependencies:
    - install
  script:
    - npm run prettier

lint:
  stage: validation
  dependencies:
    - install
  script:
    - npm run lint

jest:
  stage: validation
  dependencies:
    - install
  script:
    - npm test

build:
  stage: build
  script:
    - echo "Building site"
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main' #corre apenas nesta branch
      when: on_success #apenas se os passos anteriores for bem sucedidos
  artifacts:
    paths:
      - build/
    expire_in: 1 day

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: true
