image: node:latest

stages:
  - install
  - validation

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

prettier:
  stage: validation
  script:
    - npm run prettier

lint:
  stage: validation
  script:
    - npm run lint

jest:
  stage: validation
  script:
    - npm test
