image: node:latest

stages:
  - install
  - validation
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/ #"cache" para os módulos externos dos quais seu projeto depende.

prettier:
  stage: validation
  script:
    - npm run prettier

lint:
  stage: validation
  script:
    - npm run lint

test:
  stage: validation
  script:
    - npm run --passWithNoTests

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  rules:
    - if: "$CI_COMMIT_BRANCH == 'main'"

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      when: on_success
      allow_failure: false
